/*
 *    Copyright: This program is free software: you can redistribute it and/or
 *               modify it under the terms of the GNU General Public License as
 *               published by the Free Software Foundation; either version 3 of the
 *               License, or (at your option) any later version.
 *
 *               This program is distributed in the hope that it will be useful,
 *               but WITHOUT ANY WARRANTY; without even the implied warranty of
 *               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *               General Public License for more details.
 *
 *               You should have received a copy of the GNU General Public License
 *               along with this program.  If not, see
 *               `http://www.gnu.org/licenses/'.
 */

package org.gpicker.settings;

import org.gpicker.actions.GPickFile;
import org.openide.util.NbPreferences;

final class GPickerPanel extends javax.swing.JPanel {

    private final GPickerOptionsPanelController controller;

    GPickerPanel(GPickerOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pathTextField = new javax.swing.JTextField();
        pathLabel = new javax.swing.JLabel();
        executableLabel = new javax.swing.JLabel();
        executableTextField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(40, 20));
        setPreferredSize(new java.awt.Dimension(40, 20));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        pathTextField.setText(org.openide.util.NbBundle.getMessage(GPickerPanel.class, "GPickerPanel.pathTextField.text")); // NOI18N
        pathTextField.setMaximumSize(new java.awt.Dimension(20000, 20));
        pathTextField.setMinimumSize(new java.awt.Dimension(200, 20));
        pathTextField.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pathTextField, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(pathLabel, org.openide.util.NbBundle.getMessage(GPickerPanel.class, "GPickerPanel.pathLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(pathLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(executableLabel, org.openide.util.NbBundle.getMessage(GPickerPanel.class, "GPickerPanel.executableLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(executableLabel, gridBagConstraints);

        executableTextField.setText(org.openide.util.NbBundle.getMessage(GPickerPanel.class, "GPickerPanel.executableTextField.text")); // NOI18N
        executableTextField.setMaximumSize(new java.awt.Dimension(20000, 20));
        executableTextField.setMinimumSize(new java.awt.Dimension(200, 20));
        executableTextField.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(executableTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        pathTextField.setText(NbPreferences.forModule(GPickFile.class).get("gpicker_path", System.getenv("PATH")));
        executableTextField.setText(NbPreferences.forModule(GPickFile.class).get("gpicker_executable", "gpicker"));
    }

    void store() {
        NbPreferences.forModule(GPickFile.class).put("gpicker_path", pathTextField.getText());
        NbPreferences.forModule(GPickFile.class).put("gpicker_executable", executableTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel executableLabel;
    private javax.swing.JTextField executableTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration//GEN-END:variables
}
